// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelPaymentData, CancelPaymentErrors, CancelPaymentResponses, CreatePaymentData, CreatePaymentErrors, CreatePaymentResponses, GetPaymentData, GetPaymentErrors, GetPaymentResponses, GetPaymentStatusData, GetPaymentStatusErrors, GetPaymentStatusResponses, ListPaymentMethodsData, ListPaymentMethodsErrors, ListPaymentMethodsResponses, ListPaymentsData, ListPaymentsErrors, ListPaymentsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List payments
 *
 * Returns a paginated list of payments for your store, ordered by creation date
 * (most recent first).
 *
 * Use cursor-based pagination: if the response contains a `cursor` field, pass
 * its value as the `cursor` query parameter to fetch the next page. The absence of
 * `cursor` in the response means there are no more pages.
 *
 * Use the `status` parameter to filter payments by one or more statuses.
 *
 */
export const listPayments = <ThrowOnError extends boolean = false>(options?: Options<ListPaymentsData, ThrowOnError>) => (options?.client ?? client).get<ListPaymentsResponses, ListPaymentsErrors, ThrowOnError>({
    querySerializer: { parameters: { status: { array: { explode: false } } } },
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments',
    ...options
});

/**
 * Create a payment
 *
 * Creates a new payment for your store and returns the full payment object.
 *
 * ### Denomination
 * Specify the value the customer owes via the top-level `amount` (decimal string)
 * and `currency` (fiat code or coin ticker) fields.
 *
 * ---
 *
 * ### Preselected
 * Pass `payment_options.methods` with **exactly one entry** containing **both** `coin`
 * and `chain`. The server resolves the address immediately and returns the payment in
 * `pending` status with `paymentDetails` populated. The customer proceeds straight to
 * the deposit screen without any method selection step.
 *
 * ### Customer Choice
 * Omit `payment_options`. All store-enabled payment methods are offered to the customer
 * at checkout. The payment starts in `created` status.
 *
 * ---
 *
 * ### Supported combinations
 * | `currency` | `payment_options.methods`          | Initial status | `paymentDetails` |
 * |------------|------------------------------------|----------------|------------------|
 * | `USD`      | *(omitted)*                        | `created`      | absent           |
 * | `TON`      | *(omitted)*                        | `created`      | absent           |
 * | `USD`      | `[{coin:"USDT",chain:"TON"}]`      | `pending`      | **populated**    |
 * | `TON`      | `[{coin:"USDT",chain:"TON"}]`      | `pending`      | **populated**    |
 * | `TON`      | `[{coin:"TON",chain:"TON"}]`       | `pending`      | **populated**    |
 *
 */
export const createPayment = <ThrowOnError extends boolean = false>(options: Options<CreatePaymentData, ThrowOnError>) => (options.client ?? client).post<CreatePaymentResponses, CreatePaymentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve a payment
 *
 * Retrieves the full details of a payment by its unique identifier.
 *
 * The response structure varies by status:
 * - **`created`** — `amount`, `currency` and timer are present.
 * `paymentDetails` is absent — the customer has not yet selected a payment method.
 * - **`pending`** — `paymentDetails` is populated with the blockchain address and
 * exact coin amount. The customer must send the transfer.
 * - **`completed`** — `paymentDetails` includes `transactionSignatures` confirming
 * the on-chain transfer.
 * - **`expired`** — Elapsed TTL. Reachable from both `created` and `pending`.
 * `paymentDetails` is present only if the payment had reached `pending` first.
 * - **`cancelled`** — Canceled by the merchant. Reachable from both `created` and
 * `pending`. `paymentDetails` is present only if the payment had reached `pending`.
 *
 */
export const getPayment = <ThrowOnError extends boolean = false>(options: Options<GetPaymentData, ThrowOnError>) => (options.client ?? client).get<GetPaymentResponses, GetPaymentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments/{paymentID}',
    ...options
});

/**
 * Retrieve payment status
 *
 * Returns only the current status of a payment. Use this lightweight endpoint
 * for high-frequency polling where you only need to detect status changes
 * without the overhead of fetching the full payment object.
 *
 */
export const getPaymentStatus = <ThrowOnError extends boolean = false>(options: Options<GetPaymentStatusData, ThrowOnError>) => (options.client ?? client).get<GetPaymentStatusResponses, GetPaymentStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments/{paymentID}/status',
    ...options
});

/**
 * Cancel a payment
 *
 * Cancels a payment and returns the updated status `cancelled`.
 *
 * Cancellation is permitted from `created` or `pending` status only. Payments
 * already in a terminal state (`completed`, `expired`, or `cancelled`) cannot
 * be cancelled.
 *
 */
export const cancelPayment = <ThrowOnError extends boolean = false>(options: Options<CancelPaymentData, ThrowOnError>) => (options.client ?? client).post<CancelPaymentResponses, CancelPaymentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payments/{paymentID}/cancel',
    ...options
});

/**
 * List payment methods
 *
 * Retrieves all payment methods enabled for your store. Each entry represents
 * a unique coin + chain combination that your store accepts.
 *
 * Use `coin.symbol` and `chain.symbol` values from this response as inputs for
 * the `coin` and `chain` fields in `payment_options.methods` when creating a payment.
 *
 */
export const listPaymentMethods = <ThrowOnError extends boolean = false>(options?: Options<ListPaymentMethodsData, ThrowOnError>) => (options?.client ?? client).get<ListPaymentMethodsResponses, ListPaymentMethodsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/payment-methods',
    ...options
});
