// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.hexpay.io' | 'http://localhost/merchant' | (string & {});
};

/**
 * Top-level error envelope returned for all non-2xx responses. All error
 * information is nested under the `error` key to allow safe envelope detection
 * without inspecting the HTTP status code.
 *
 */
export type ErrorResponse = {
    error: Error;
};

/**
 * Structured error object. `type` gives the broad category, `code` is the
 * machine-readable discriminator for programmatic handling, `message` is a
 * human-readable explanation, and the optional `param` names the specific
 * request field that caused the error.
 *
 */
export type Error = {
    /**
     * High-level error category. Use this to determine the general class of
     * the error without parsing `code`.
     *
     */
    type: 'invalid_request_error' | 'authentication_error' | 'not_found_error' | 'rate_limit_error' | 'api_error';
    /**
     * Human-readable description of the error, intended for developers.
     */
    message: string;
    /**
     * Machine-readable error identifier. Use this in conditional logic to branch
     * on specific error conditions (e.g., retry on `rate_limit_exceeded`,
     * surface to user on `payment_not_cancellable`).
     *
     */
    code: string;
    /**
     * The name of the request field that caused the error, using dot notation
     * for nested fields (e.g., `currency`, `payment_options.methods[0]`).
     * Present only when the error is attributable to a specific parameter.
     *
     */
    param?: string;
};

/**
 * Request body for creating a new payment. The body is intentionally flat:
 * `amount`, `currency`, and all optional fields are top-level. The only nested
 * structure is `payment_options.methods`, which describes an allowlist of
 * acceptable payment methods.
 *
 */
export type CreatePaymentRequest = {
    /**
     * The payment value as a positive decimal string. No leading zeros are
     * permitted on the integer part (`"007"` is invalid; use `"7"`).
     * For fiat currencies up to 2 decimal places are recommended.
     * For crypto tickers precision depends on the coin.
     *
     */
    amount: string;
    /**
     * Ticker symbol for the denomination. Accepts fiat codes (e.g. `USD`, `EUR`,
     * `RUB`) or TON-ecosystem coin tickers (e.g. `TON`, `USDT`).
     *
     * This field defines the **unit of value** — it does not determine the coin
     * the customer pays with. Payment coin is controlled by `payment_options.methods`.
     *
     * For the full list of accepted values use `GET /v1/payment-methods` (coins)
     * or refer to the supported fiat codes in your store settings.
     *
     */
    currency: string;
    payment_options?: PaymentOptions;
    /**
     * Time-to-live in seconds. Defines how long the payment remains active
     * from the moment of creation. Once the TTL elapses the payment moves to
     * `expired` status — this can happen from either `created` or `pending`.
     *
     * Minimum: `900` (15 minutes). Maximum: `43200` (12 hours).
     * Defaults to `3600` (1 hour) if not specified.
     *
     */
    ttl?: number;
    /**
     * Merchant-defined external order identifier. Use this to correlate a HexPay
     * payment with your internal order or invoice system. Returned on all payment
     * objects and included in webhook payloads.
     *
     */
    order_id?: string;
    /**
     * Human-readable description of the payment purpose. May be displayed to
     * the customer on the payment page.
     *
     */
    description?: string;
    /**
     * Arbitrary key-value pairs for merchant use. All values must be strings.
     * Returned on all payment objects and included in webhook payloads.
     * Maximum 10 keys; key names up to 64 characters, values up to 512 characters.
     *
     */
    metadata?: {
        [key: string]: string;
    };
    /**
     * HTTPS URL to which HexPay will POST webhook notifications for this
     * payment's lifecycle events (e.g., transitions to `pending` or `completed`).
     *
     * Requirements:
     * - Must use HTTPS. Plain HTTP URLs are rejected.
     * - Must be publicly reachable from the internet. Loopback addresses
     * (`localhost`, `127.x.x.x`) and private network ranges (`10.x.x.x`,
     * `192.168.x.x`, `172.16–31.x.x`) are not allowed.
     * - Make sure your server is configured to accept POST requests at this URL
     * before creating payments.
     *
     */
    webhookURL?: string;
};

/**
 * Optional constraints on which payment methods are available at checkout.
 * When omitted entirely, all payment methods enabled for your store are shown
 * and the payment is created in `created` status.
 *
 */
export type PaymentOptions = {
    /**
     * Exactly one method filter specifying both `coin` and `chain`.
     * When provided, the payment is created directly in `pending` status with
     * `paymentDetails` populated (Preselected).
     *
     * Omit this field entirely to let the customer select a payment method
     * at checkout — payment starts in `created` status (Customer Choice).
     *
     */
    methods?: [
        MethodFilter
    ];
};

/**
 * A method filter specifying exactly which coin and chain to use for payment.
 * Both `coin` and `chain` are required.
 *
 * Use the exact `symbol` values returned by `GET /v1/payment-methods`.
 * Values are case-sensitive.
 *
 */
export type MethodFilter = {
    /**
     * Coin ticker to match. Must be a coin supported by HexPay on TON.
     */
    coin: 'BUILD' | 'BLUM' | 'DOGS' | 'DUST' | 'DYOR' | 'NOT' | 'STON' | 'TON' | 'USDT' | 'XAUt0';
    /**
     * Chain ticker to match. Currently only `TON` is supported.
     */
    chain: 'TON';
};

/**
 * Lifecycle status of a payment:
 * - `created`   — Payment created; customer has not yet selected a payment method.
 * `paymentDetails` is absent.
 * - `pending`   — Method confirmed; `paymentDetails` populated with the blockchain
 * address and exact coin amount. Awaiting on-chain transfer.
 * - `completed` — On-chain transfer confirmed. `transactionSignatures` are present.
 * - `expired`   — Payment TTL elapsed without a confirmed transfer. Reachable from
 * **both** `created` (customer never selected a method) and `pending` (customer
 * selected but did not send the transfer in time).
 * - `cancelled` — Canceled by the merchant via `POST /v1/payments/{id}/cancel`.
 * Reachable from both `created` and `pending`.
 *
 */
export type PaymentStatus = 'created' | 'pending' | 'completed' | 'expired' | 'cancelled';

/**
 * Lightweight response containing only the current status of a payment.
 * Use `GET /v1/payments/{paymentID}` when you also need the address,
 * amount, or timer details.
 *
 */
export type PaymentStatusResponse = {
    status: PaymentStatus;
};

export type PaymentCancelResponse = {
    status: PaymentStatus;
};

/**
 * Paginated list of payments with cursor-based navigation metadata.
 */
export type PaymentListResponse = {
    /**
     * Array of payment objects for the current page.
     */
    payments: Array<PaymentResponse>;
    /**
     * Opaque pagination cursor. Present only when there are more pages of results.
     * Pass this value as the `cursor` query parameter to retrieve the next page.
     * When absent, the current page is the last one.
     *
     */
    cursor?: string;
};

/**
 * Full payment object. Returned by the create, retrieve, list, and cancel endpoints.
 *
 */
export type PaymentResponse = {
    /**
     * Unique payment identifier.
     */
    id: string;
    status: PaymentStatus;
    /**
     * The denomination amount recorded at creation time. Mirrors the `amount`
     * field from the create request.
     *
     */
    amount: string;
    /**
     * The denomination currency ticker recorded at creation time. Mirrors the
     * `currency` field from the create request. May be a fiat code or a coin ticker.
     *
     */
    currency: string;
    paymentDetails?: PaymentDetails;
    /**
     * URL of the HexPay-hosted checkout page for this payment. Redirect the
     * customer to this URL to let them complete the payment.
     *
     */
    checkoutURL: string;
    /**
     * Merchant-defined external order identifier, if provided at creation.
     */
    order_id?: string;
    /**
     * Payment description
     */
    description?: string;
    timer: PaymentTimerResponse;
};

/**
 * Lifecycle timing information for the payment.
 *
 */
export type PaymentTimerResponse = {
    /**
     * Payment creation timestamp in RFC 3339 format (UTC).
     */
    createdAt: string;
    /**
     * Timestamp (RFC 3339, UTC) at which the payment automatically moves to
     * `expired` status. Subtract `createdAt` to derive the total TTL window.
     *
     */
    expiresAt: string;
    /**
     * Timestamp (RFC 3339, UTC) at which the payment has been paid
     *
     */
    paidAt?: string;
};

/**
 * Cryptocurrency payment instructions. Populated when the payment transitions
 * from `created` to `pending`.
 *
 * The customer must send exactly `coinAmount` of `coin` to `address` on the
 * TON blockchain.
 *
 */
export type PaymentDetails = {
    /**
     * TON blockchain address the customer must send the cryptocurrency to.
     */
    address: string;
    /**
     * Exact cryptocurrency amount the customer must transfer. Sending less
     * than this amount will result in an underpayment.
     *
     */
    coinAmount: string;
    coin: CoinResponse;
    chain: ChainResponse;
    /**
     * On-chain transaction hash(es) confirming the payment.
     * Present only when status is `completed`.
     *
     */
    transactionSignatures?: Array<string>;
};

/**
 * Cryptocurrency (coin) metadata.
 */
export type CoinResponse = {
    /**
     * Human-readable name of the cryptocurrency.
     */
    name: string;
    /**
     * Ticker symbol. Use this value as the `coin` field in
     * `payment_options.methods` when creating payments.
     *
     */
    symbol: 'BUILD' | 'BLUM' | 'DOGS' | 'DUST' | 'DYOR' | 'NOT' | 'STON' | 'TON' | 'USDT' | 'XAUt0';
    /**
     * URL of the coin logo image.
     */
    imgUrl: string;
};

/**
 * Blockchain network metadata. Currently only TON is supported.
 */
export type ChainResponse = {
    /**
     * Human-readable name of the blockchain network.
     */
    name: string;
    /**
     * Ticker symbol. Use this value as the `chain` field in
     * `payment_options.methods` when creating payments.
     *
     */
    symbol: 'TON';
    /**
     * URL of the chain logo image.
     */
    imgUrl: string;
};

/**
 * List of all payment methods currently enabled for the store, wrapped in a
 * consistent data envelope. Use `coin.symbol` and `chain.symbol` from each entry
 * as filter inputs in `payment_options.methods` when creating payments.
 *
 */
export type PaymentMethodListResponse = {
    /**
     * Array of enabled payment method objects.
     */
    data: Array<PaymentMethodResponse>;
};

/**
 * A single payment method — a coin + chain combination accepted by the store.
 * The `coin.symbol` / `chain.symbol` pair uniquely identifies the method for
 * use in `payment_options.methods` filters.
 *
 */
export type PaymentMethodResponse = {
    /**
     * Unique identifier for this payment method configuration.
     */
    id: string;
    coin: CoinResponse;
    chain: ChainResponse;
};

/**
 * Unique UUID v4 key for idempotent request processing. If the server receives
 * two requests with the same key within a 24-hour window, the second returns
 * the cached response from the first without creating a duplicate resource.
 * Generate a fresh key for each logically distinct operation.
 *
 */
export type IdempotencyKey = string;

/**
 * Unique identifier of the payment (UUID).
 */
export type PaymentId = string;

export type ListPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of payment objects to return per page.
         * Accepts values between 1 and 100. Defaults to 10.
         *
         */
        limit?: number;
        /**
         * Pagination cursor. Pass the value of `cursor` from the previous
         * response to retrieve the next page of results.
         *
         */
        cursor?: string;
        /**
         * Filter payments by status. Accepts a comma-separated list of statuses.
         * Returns payments matching **any** of the provided values.
         * Omit to return payments in all statuses.
         *
         */
        status?: Array<PaymentStatus>;
    };
    url: '/v1/payments';
};

export type ListPaymentsErrors = {
    /**
     * One or more query parameters are invalid.
     */
    400: ErrorResponse;
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type ListPaymentsError = ListPaymentsErrors[keyof ListPaymentsErrors];

export type ListPaymentsResponses = {
    /**
     * A paginated list of payments.
     */
    200: PaymentListResponse;
};

export type ListPaymentsResponse = ListPaymentsResponses[keyof ListPaymentsResponses];

export type CreatePaymentData = {
    body: CreatePaymentRequest;
    headers?: {
        /**
         * Unique UUID v4 key for idempotent request processing. If the server receives
         * two requests with the same key within a 24-hour window, the second returns
         * the cached response from the first without creating a duplicate resource.
         * Generate a fresh key for each logically distinct operation.
         *
         */
        'X-Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/payments';
};

export type CreatePaymentErrors = {
    /**
     * The request is invalid or contains conflicting parameters.
     */
    400: ErrorResponse;
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * A referenced resource (e.g., currency) was not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit or concurrent payment quota exceeded.
     */
    429: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type CreatePaymentError = CreatePaymentErrors[keyof CreatePaymentErrors];

export type CreatePaymentResponses = {
    /**
     * Payment created successfully. Returns the full payment object.
     * Status is `created` unless a single exact method was specified via
     * `payment_options.methods`, in which case status is `pending` and
     * `paymentDetails` is already populated.
     *
     */
    201: PaymentResponse;
};

export type CreatePaymentResponse = CreatePaymentResponses[keyof CreatePaymentResponses];

export type GetPaymentData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the payment (UUID).
         */
        paymentID: string;
    };
    query?: never;
    url: '/v1/payments/{paymentID}';
};

export type GetPaymentErrors = {
    /**
     * The provided paymentID is not a valid UUID.
     */
    400: ErrorResponse;
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * Payment not found.
     */
    404: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type GetPaymentError = GetPaymentErrors[keyof GetPaymentErrors];

export type GetPaymentResponses = {
    /**
     * Payment details retrieved successfully.
     */
    200: PaymentResponse;
};

export type GetPaymentResponse = GetPaymentResponses[keyof GetPaymentResponses];

export type GetPaymentStatusData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the payment (UUID).
         */
        paymentID: string;
    };
    query?: never;
    url: '/v1/payments/{paymentID}/status';
};

export type GetPaymentStatusErrors = {
    /**
     * The provided paymentID is not a valid UUID.
     */
    400: ErrorResponse;
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * Payment not found.
     */
    404: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type GetPaymentStatusError = GetPaymentStatusErrors[keyof GetPaymentStatusErrors];

export type GetPaymentStatusResponses = {
    /**
     * Payment status retrieved successfully.
     */
    200: PaymentStatusResponse;
};

export type GetPaymentStatusResponse = GetPaymentStatusResponses[keyof GetPaymentStatusResponses];

export type CancelPaymentData = {
    body?: never;
    headers?: {
        /**
         * Unique UUID v4 key for idempotent request processing. If the server receives
         * two requests with the same key within a 24-hour window, the second returns
         * the cached response from the first without creating a duplicate resource.
         * Generate a fresh key for each logically distinct operation.
         *
         */
        'X-Idempotency-Key'?: string;
    };
    path: {
        /**
         * Unique identifier of the payment (UUID).
         */
        paymentID: string;
    };
    query?: never;
    url: '/v1/payments/{paymentID}/cancel';
};

export type CancelPaymentErrors = {
    /**
     * The request is invalid or the payment cannot be cancelled in its current state.
     */
    400: ErrorResponse;
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * Payment not found.
     */
    404: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type CancelPaymentError = CancelPaymentErrors[keyof CancelPaymentErrors];

export type CancelPaymentResponses = {
    /**
     * Payment cancelled successfully.
     *
     */
    200: PaymentCancelResponse;
};

export type CancelPaymentResponse = CancelPaymentResponses[keyof CancelPaymentResponses];

export type ListPaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/payment-methods';
};

export type ListPaymentMethodsErrors = {
    /**
     * Authentication failed — token is missing, invalid, or expired.
     */
    401: ErrorResponse;
    /**
     * An unexpected internal server error occurred.
     */
    500: ErrorResponse;
};

export type ListPaymentMethodsError = ListPaymentMethodsErrors[keyof ListPaymentMethodsErrors];

export type ListPaymentMethodsResponses = {
    /**
     * Payment methods retrieved successfully.
     */
    200: PaymentMethodListResponse;
};

export type ListPaymentMethodsResponse = ListPaymentMethodsResponses[keyof ListPaymentMethodsResponses];
